import React from "react";
import { ReactComponent as DataSvg } from "./data.svg";
import { ReactComponent as HomeSvg } from "./home.svg";
import { ReactComponent as UsersSvg } from "./users.svg";
import { ReactComponent as SearchSvg } from "./search.svg";
import { ReactComponent as SingOutSvg } from "./sing-out.svg";
import { ReactComponent as ArrowDownSvg } from "./arrow-down.svg";
import { ReactComponent as ForwardSvg } from "./forward.svg";
import { ReactComponent as BottomMenuSvg } from "./bottom-menu.svg";
import { ReactComponent as PencilSvg } from "./pencil.svg";
import { ReactComponent as CloseSvg } from "./close.svg";
import { ReactComponent as EyeSvg } from "./eye.svg";
import { ReactComponent as PlusSvg } from "./plus.svg";
import { ReactComponent as MinusSvg } from "./minus.svg";
import { ReactComponent as TrashSvg } from "./trash.svg";
import { ReactComponent as AppSvg } from "./app.svg";
import { ReactComponent as ArrowUpSvg } from "./arrow-up.svg";
import { ReactComponent as ClipSvg } from "./clip.svg";
import { ReactComponent as DownloadSvg } from "./download.svg";
import { ReactComponent as CustomRedoSvg } from "./custom-redo.svg";
import { ReactComponent as CustomUndoSvg } from "./custom-undo.svg";
import { ReactComponent as LockSvg } from "./lock.svg";
import { ReactComponent as ConfigSvg } from "./config.svg";
import { ReactComponent as UnfoldMoreSvg } from "./unfold-more.svg";
import { ReactComponent as UnfoldLessSvg } from "./unfold-less.svg";
import { ReactComponent as СalendarSvg } from "./calendar.svg";
import { ReactComponent as DmgFormatSvg } from "./dmg-format.svg";
import { ReactComponent as SliderFormatSvg } from "./slider-format.svg";
import { ReactComponent as TxtFormatSvg } from "./txt-format.svg";
import { ReactComponent as ZipFormatSvg } from "./zip-format.svg";
import { ReactComponent as NotificationsSvg } from "./notifications.svg";

import { Icon } from "./Icon";

export const UnfoldMoreIcon = (props: any) => <Icon IconSvg={UnfoldMoreSvg} {...props} />;
export const UnfoldLessIcon = (props: any) => <Icon IconSvg={UnfoldLessSvg} {...props} />;
export const ConfigIcon = (props: any) => <Icon IconSvg={ConfigSvg} {...props} />;
export const DataIcon = (props: any) => <Icon IconSvg={DataSvg} {...props} />;
export const HomeIcon = (props: any) => <Icon IconSvg={HomeSvg} {...props} />;
export const UsersIcon = (props: any) => <Icon IconSvg={UsersSvg} {...props} />;
export const SearchIcon = (props: any) => <Icon IconSvg={SearchSvg} {...props} />;
export const SingOutIcon = (props: any) => <Icon IconSvg={SingOutSvg} {...props} />;
export const ArrowDownIcon = (props: any) => <Icon IconSvg={ArrowDownSvg} {...props} />;
export const ForwardIcon = (props: any) => <Icon IconSvg={ForwardSvg} {...props} />;
export const BottomMenuIcon = (props: any) => <Icon IconSvg={BottomMenuSvg} {...props} />;
export const PencilIcon = (props: any) => <Icon IconSvg={PencilSvg} {...props} />;
export const CloseIcon = (props: any) => <Icon IconSvg={CloseSvg} {...props} />;
export const EyeIcon = (props: any) => <Icon IconSvg={EyeSvg} {...props} />;
export const PlusIcon = (props: any) => <Icon IconSvg={PlusSvg} {...props} />;
export const MinusIcon = (props: any) => <Icon IconSvg={MinusSvg} {...props} />;
export const TrashIcon = (props: any) => <Icon IconSvg={TrashSvg} {...props} />;
export const AppIcon = (props: any) => <Icon IconSvg={AppSvg} {...props} />;
export const LockIcon = (props: any) => <Icon IconSvg={LockSvg} {...props} />;
export const ArrowUpIcon = (props: any) => <Icon IconSvg={ArrowUpSvg} {...props} />;
export const ClipIcon = (props: any) => <Icon IconSvg={ClipSvg} {...props} />;
export const DownloadIcon = (props: any) => <Icon IconSvg={DownloadSvg} {...props} />;
export const CustomRedoIcon = (props: any) => <Icon IconSvg={CustomRedoSvg} {...props} />;
export const CustomUndoIcon = (props: any) => <Icon IconSvg={CustomUndoSvg} {...props} />;
export const СalendarIcon = (props: any) => <Icon IconSvg={СalendarSvg} {...props} />;
export const DmgFormatIcon = (props: any) => <Icon IconSvg={DmgFormatSvg} {...props} />;
export const SliderFormatIcon = (props: any) => <Icon IconSvg={SliderFormatSvg} {...props} />;
export const TxtFormatIcon = (props: any) => <Icon IconSvg={TxtFormatSvg} {...props} />;
export const ZipFormatIcon = (props: any) => <Icon IconSvg={ZipFormatSvg} {...props} />;
export const NotificationsIcon = (props: any) => <Icon IconSvg={NotificationsSvg} {...props} />;
